name = "Brutus"
uuid = "44ccd279-0a44-4492-af09-0e34b2907bcc"
authors = ["Valentin Churavy <v.churavy@gmail.com>", "Leon Shen <leon@yhls.org>"]
version = "0.1.0"

[deps]
MLIR = "bfde9dd4-8f40-4a1e-be09-1475335e1c92"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
julia = "1.8"
