name = "Brutus"
uuid = "44ccd279-0a44-4492-af09-0e34b2907bcc"
authors = ["Valentin Churavy <v.churavy@gmail.com>", "Leon Shen <leon@yhls.org>"]
version = "0.1.0"

[deps]
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[compat]
julia = "1.3"
