name: Brutus CI

on: [push]

jobs:
  test:
    name: Test on os ${{ matrix.os }} and Julia ${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.1, 1.4.0-rc2]
        os: [ubuntu-18.04]
    
    steps:
      - uses: actions/checkout@v1
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v0.2
        with:
          version: ${{ matrix.julia-version }}
      - run: julia --project=Brutus -e 'using Pkg; pkg"instantiate"; pkg"precompile"'
