name: Brutus CI

on: [push]

jobs:
  test:
    name: Test on os ${{ matrix.os }} and Julia ${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.1]
        os: [ubuntu-18.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodule
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Configure build
        run: |
          cmake -S llvm-project/llvm -B build \
                -DLLVM_ENABLE_PROJECTS="mlir" -DLLVM_TARGETS_TO_BUILD="host;NVPTX" \
                -DLLVM_EXTERNAL_PROJECTS="brutus" -DLLVM_EXTERNAL_BRUTUS_SOURCE_DIR="." \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build library
        run: cmake --build build --target brutus --parallel `nproc`

      - name: Precompile library
        run: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`pwd`/build/lib
          julia --project=Brutus -e 'using Pkg; pkg"instantiate"; pkg"precompile"'

      - name: Test brutus
        run: cmake --build build --target check-brutus --parallel `nproc`

