name: Update submodules

on: 
  schedule:
    - cron: '00 00 * * *'

jobs:
  Submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodule
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Update submodules
        run: |
          git -C llvm-project pull
            - name: Create Pull Request
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update submodules
          committer: Valentin Churavy <vchuravy@users.noreply.github.com>
          author: Valentin Churavy <vchuravy@users.noreply.github.com>
          title: '[Submodules] Nightly update'

